// Auto-generated Nuxt imports
declare global {
  // Vue 3 Composition API
  const ref: typeof import('vue')['ref']
  const reactive: typeof import('vue')['reactive']
  const computed: typeof import('vue')['computed']
  const readonly: typeof import('vue')['readonly']
  const watch: typeof import('vue')['watch']
  const watchEffect: typeof import('vue')['watchEffect']
  const unref: typeof import('vue')['unref']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const isRef: typeof import('vue')['isRef']
  const customRef: typeof import('vue')['customRef']
  const triggerRef: typeof import('vue')['triggerRef']
  const shallowRef: typeof import('vue')['shallowRef']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const markRaw: typeof import('vue')['markRaw']
  const effectScope: typeof import('vue')['effectScope']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onMounted: typeof import('vue')['onMounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onActivated: typeof import('vue')['onActivated']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const provide: typeof import('vue')['provide']
  const inject: typeof import('vue')['inject']
  const nextTick: typeof import('vue')['nextTick']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineCustomElement: typeof import('vue')['defineCustomElement']
  const defineSSRCustomElement: typeof import('vue')['defineSSRCustomElement']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const h: typeof import('vue')['h']
  const createApp: typeof import('vue')['createApp']
  const createSSRApp: typeof import('vue')['createSSRApp']
  const isReadonly: typeof import('vue')['isReadonly']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const toRaw: typeof import('vue')['toRaw']

  // Nuxt 3 composables
  const useHead: typeof import('#app')['useHead']
  const useSeoMeta: typeof import('#app')['useSeoMeta']
  const useRouter: typeof import('#app')['useRouter']
  const useRoute: typeof import('#app')['useRoute']
  const navigateTo: typeof import('#app')['navigateTo']
  const useRuntimeConfig: typeof import('#app')['useRuntimeConfig']
  const useState: typeof import('#app')['useState']
  const useCookie: typeof import('#app')['useCookie']
  const useFetch: typeof import('#app')['useFetch']
  const useLazyFetch: typeof import('#app')['useLazyFetch']
  const $fetch: typeof import('#app')['$fetch']
  const refresh: typeof import('#app')['refresh']
  const clearError: typeof import('#app')['clearError']
  const createError: typeof import('#app')['createError']
  const isNuxtError: typeof import('#app')['isNuxtError']
  const throwError: typeof import('#app')['throwError']
  const clearNuxtData: typeof import('#app')['clearNuxtData']
  const refreshCookie: typeof import('#app')['refreshCookie']
  const readBody: typeof import('#app')['readBody']
  const getQuery: typeof import('#app')['getQuery']
  const getRouterParam: typeof import('#app')['getRouterParam']
  const getRouterParams: typeof import('#app')['getRouterParams']
  const definePageMeta: typeof import('#app')['definePageMeta']
  const defineNuxtRouteMiddleware: typeof import('#app')['defineNuxtRouteMiddleware']
  const defineNuxtPlugin: typeof import('#app')['defineNuxtPlugin']
  const addRouteMiddleware: typeof import('#app')['addRouteMiddleware']
  const useNuxtApp: typeof import('#app')['useNuxtApp']
  const useNuxtData: typeof import('#app')['useNuxtData']
  const useAsyncData: typeof import('#app')['useAsyncData']
  const useLazyAsyncData: typeof import('#app')['useLazyAsyncData']
  const useRequestHeaders: typeof import('#app')['useRequestHeaders']
  const useRequestEvent: typeof import('#app')['useRequestEvent']
  const useRequestFetch: typeof import('#app')['useRequestFetch']
  const useRequestURL: typeof import('#app')['useRequestURL']
  const useResponseHeader: typeof import('#app')['useResponseHeader']
  const preloadComponents: typeof import('#app')['preloadComponents']
  const prefetchComponents: typeof import('#app')['prefetchComponents']
  const preloadRouteComponents: typeof import('#app')['preloadRouteComponents']
  const isPrerendered: typeof import('#app')['isPrerendered']
  const loadPayload: typeof import('#app')['loadPayload']
  const preloadPayload: typeof import('#app')['preloadPayload']
  const definePayloadReducer: typeof import('#app')['definePayloadReducer']
  const definePayloadReviver: typeof import('#app')['definePayloadReviver']
  const setPageLayout: typeof import('#app')['setPageLayout']
  const reloadNuxtApp: typeof import('#app')['reloadNuxtApp']
  
  // Color Mode
  const useColorMode: typeof import('@nuxtjs/color-mode')['useColorMode']

  // VueUse composables  
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage']
  const useSessionStorage: typeof import('@vueuse/core')['useSessionStorage']
  const useToggle: typeof import('@vueuse/core')['useToggle']
  const useClipboard: typeof import('@vueuse/core')['useClipboard']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useDark: typeof import('@vueuse/core')['useDark']
  const usePreferredDark: typeof import('@vueuse/core')['usePreferredDark']
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize']
  const useMedia: typeof import('@vueuse/core')['useMedia']
  const useBreakpoints: typeof import('@vueuse/core')['useBreakpoints']
  const useMagicKeys: typeof import('@vueuse/core')['useMagicKeys']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useCounter: typeof import('@vueuse/core')['useCounter']
  const useTitle: typeof import('@vueuse/core')['useTitle']
  const useFavicon: typeof import('@vueuse/core')['useFavicon']
  const useNetwork: typeof import('@vueuse/core')['useNetwork']
  const useOnline: typeof import('@vueuse/core')['useOnline']
  const useGeolocation: typeof import('@vueuse/core')['useGeolocation']
  const useBattery: typeof import('@vueuse/core')['useBattery']
  const useDevicesList: typeof import('@vueuse/core')['useDevicesList']
  const usePermission: typeof import('@vueuse/core')['usePermission']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useWebWorker: typeof import('@vueuse/core')['useWebWorker']
  const useWebWorkerFn: typeof import('@vueuse/core')['useWebWorkerFn']
  const useFileDialog: typeof import('@vueuse/core')['useFileDialog']
  const useDropZone: typeof import('@vueuse/core')['useDropZone']
  const useAsyncValidator: typeof import('@vueuse/core')['useAsyncValidator']
  const useConfirmDialog: typeof import('@vueuse/core')['useConfirmDialog']
  const useImage: typeof import('@vueuse/core')['useImage']
  const useInfiniteScroll: typeof import('@vueuse/core')['useInfiniteScroll']
  const useIntersectionObserver: typeof import('@vueuse/core')['useIntersectionObserver']
  const useLazyLoad: typeof import('@vueuse/core')['useLazyLoad']
  const useVirtualList: typeof import('@vueuse/core')['useVirtualList']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useMutationObserver: typeof import('@vueuse/core')['useMutationObserver']
  const useEventSource: typeof import('@vueuse/core')['useEventSource']
  const useFetch: typeof import('@vueuse/core')['useFetch']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']

  // Components
  const defineProps: typeof import('vue')['defineProps']
  const defineEmits: typeof import('vue')['defineEmits']
  const defineExpose: typeof import('vue')['defineExpose']
  const withDefaults: typeof import('vue')['withDefaults']

  // Utils
  const $: typeof import('#app')['$']
  
  interface ComponentCustomProperties {}
  interface GlobalComponents {}
}

export {}